# Cloud Build configuration for building, pushing, and deploying a Flask app.

steps:
# 1. Build the container image.
- name: "gcr.io/cloud-builders/docker"
  args: [
    "build",
    "-t", "us-central1-docker.pkg.dev/shaped-pride-471520-p5/cicd-example/my-flask-app:latest",
    "."
  ]

# 2. Push the container image to Artifact Registry.
- name: "gcr.io/cloud-builders/docker"
  args: [
    "push",
    "us-central1-docker.pkg.dev/shaped-pride-471520-p5/cicd-example/my-flask-app:latest"
  ]

# 3. Deploy the container image to Cloud Run.
- name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
  entrypoint: gcloud
  args:
    - run
    - deploy
    - my-flask-app-service
    - --image=us-central1-docker.pkg.dev/shaped-pride-471520-p5/cicd-example/my-flask-app:latest
    - --region=us-central1
    - --platform=managed
    - --allow-unauthenticated

# List the images produced by the build.
images:
- "us-central1-docker.pkg.dev/shaped-pride-471520-p5/cicd-example/my-flask-app:latest"

# Configure logging to use Cloud Logging only.
options:
  logging: CLOUD_LOGGING_ONLY
